/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Stan (https://sketchfab.com/Stas_SayHallo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/gandhi-2d802195370c46f784827142022b61ce
Title: Gandhi
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eyes/scene.gltf')
  return (
    <group position={props.position} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.glasses_02_low_Gandi_0.geometry} material={materials.Gandi} position={[0, 0, -0.233]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.glasses_01_low_01_Gandi_0.geometry} material={materials.Gandi} position={[0, 0, -1.055]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.mustache_low_Gandi_0.geometry} material={materials.Gandi} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.eyebrows_low_Gandi_0.geometry} material={materials.Gandi} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.body_low_Gandi_0.geometry} material={materials.Gandi} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.glasses_01_low_02_Gandi_0.geometry} material={materials.Gandi} position={[0, 0, -1.055]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
          <mesh geometry={nodes.eyes_eye_0.geometry} material={materials.material} position={[-42.818, 272.563, -82.593]} rotation={props.rotation} scale={16.874} />
          <mesh geometry={nodes.glasses_03_low_glass_0.geometry} material={materials.glass} position={[0, 0, -0.233]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
