/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: jared the goober (https://sketchfab.com/jared2024_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/upgraded-scientist-head-spidarrund-3cc072b275784c97bb88380e7b98af3f
Title: Upgraded Scientist Head (Spidarrund)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/beard/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0, -143.571]} rotation={[-1.442, 0, 0]} scale={5.393}>
          <mesh geometry={nodes.scientist_02_base_male_wtie_28smd_eyeball_r_0.geometry} material={materials.eyeball_r} />
          <mesh geometry={nodes.scientist_02_base_male_wtie_28smd_eyeball_l_0.geometry} material={materials.eyeball_l} />
          <mesh geometry={nodes.scientist_02_base_male_wtie_28smd_mouth_0.geometry} material={materials.mouth} />
          <mesh geometry={nodes.scientist_02_base_male_wtie_28smd_Base_M_28_D_0.geometry} material={materials.Base_M_28_D} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={893.482}>
          <mesh geometry={nodes.braindance_headsetsmd_outer_headset_0.geometry} material={materials.outer_headset} />
          <mesh geometry={nodes.braindance_headsetsmd_inner_cups_0.geometry} material={materials.inner_cups} />
          <mesh geometry={nodes.braindance_headsetsmd_inner_circuits_0.geometry} material={materials.inner_circuits} />
          <mesh geometry={nodes.braindance_headsetsmd_inner_headset_0.geometry} material={materials.inner_headset} />
          <mesh geometry={nodes.braindance_headsetsmd_upper_cups_0.geometry} material={materials.upper_cups} />
          <mesh geometry={nodes.braindance_headsetsmd_back_insert2_0.geometry} material={materials.back_insert2} />
          <mesh geometry={nodes.braindance_headsetsmd_back_insert_0.geometry} material={materials.back_insert} />
          <mesh geometry={nodes.braindance_headsetsmd_misc_screws_0.geometry} material={materials.misc_screws} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={893.482}>
          <mesh geometry={nodes.blank_side_text_0.geometry} material={materials.side_text} />
          <mesh geometry={nodes.blank_braindance_logo_0.geometry} material={materials.braindance_logo} />
          <mesh geometry={nodes.blank_outer_headset_0.geometry} material={materials.outer_headset} />
        </group>
        <group position={[158.801, 1716.516, 327.775]} rotation={[0.153, -0.491, -3.084]} scale={485.078}>
          <mesh geometry={nodes.jul13_se_headset_spydmx001_modelsworkshopplayeritemsall_classjul13_se_headsetjul_0.geometry} material={materials.modelsworkshopplayeritemsall_classjul13_se_headsetjul} />
          <mesh geometry={nodes.jul13_se_headset_spydmx001_modelsworkshopplayeritemsall_classjul13_se_headsetjul13_s_0.geometry} material={materials.modelsworkshopplayeritemsall_classjul13_se_headsetjul13_s} />
        </group>
        <group position={[435.421, 286.174, 3.386]} rotation={[0, 0.059, 0.745]} scale={751.273}>
          <mesh geometry={nodes.jul13_se_headset_spydmx002_modelsworkshopplayeritemsall_classjul13_se_headsetjul_0.geometry} material={materials.modelsworkshopplayeritemsall_classjul13_se_headsetjul} />
          <mesh geometry={nodes.jul13_se_headset_spydmx002_modelsworkshopplayeritemsall_classjul13_se_headsetjul13_s_0.geometry} material={materials.modelsworkshopplayeritemsall_classjul13_se_headsetjul13_s} />
        </group>
        <mesh geometry={nodes.part_2smd_astro_helmet_0.geometry} material={materials.astro_helmet} position={[9.799, 431.307, 207.141]} rotation={[-Math.PI / 2, 0, 0]} scale={3221.191} />
        <mesh geometry={nodes.scientist_02_glasses_roundsmd_glasses_d_0.geometry} material={materials.glasses_d} position={[6.811, 467.319, -35.189]} rotation={[-Math.PI / 2, 0, 0]} scale={54.205} />
        <mesh geometry={nodes.Icosphere__0.geometry} material={materials.Icosphere__0} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Icosphere001__0.geometry} material={materials.Icosphere__0} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Icosphere002__0.geometry} material={materials.Icosphere__0} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Object_10_Material_16_0.geometry} material={materials.Material_16} position={[48.695, -1590.443, -970.214]} rotation={[3.14, 0.093, 0]} scale={433.161} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
