/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: ardhanaputra (https://sketchfab.com/ardhanaputra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cool-man-ad14b71697dd4ea7836c1f06c75e5f72
Title: Cool Man
*/

import React, {forwardRef, useEffect, useImperativeHandle} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export const Model = forwardRef((props,ref) => {
  const group = React.useRef()
  const headRef = React.useRef()

  const { scene, animations } = useGLTF('/man/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions && animations.length > 0) {
      const actionName = animations[props.animationNumber ?? 1].name // Берем вторую анимацию
      console.log(animations)
      actions[actionName]?.play() // Запускаем анимацию
    }
  }, [actions, animations])
  useImperativeHandle(ref, () => ({
    getModel: () => group.current,
  }));
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.966}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_178">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Object_11_168" />
                  <group name="Object_13_169" />
                  <group name="Object_15_170" />
                  <group name="Object_17_171" />
                  <group name="Object_19_172" />
                  <group name="Object_21_173" />
                  <group name="Object_23_174" />
                  <group name="Object_25_175" />
                  <group name="Object_7_176" />
                  <group name="Object_9_177" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Wolf3D_Skin.003']} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Wolf3D_Teeth.003']} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Wolf3D_Body.003']} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Wolf3D_Outfit_Bottom.003']} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['Wolf3D_Outfit_Footwear.003']} skeleton={nodes.Object_15.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['Wolf3D_Outfit_Top.003']} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['Wolf3D_Hair.003']} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} ref={headRef} material={materials['Wolf3D_Glasses.003']} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['Wolf3D_Eye.003']} skeleton={nodes.Object_23.skeleton} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials['Wolf3D_Eye.003']} skeleton={nodes.Object_25.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/man/scene.gltf')
