/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: CHANO (https://sketchfab.com/pedroribeiro.1104)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/de-dust2-935c47ecc9574a29a72df694c4f84d5d
Title: De_dust2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('dust_2/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI/ 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Model001_Material628} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Model001_Material628_0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Model001_Material628_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Model001_Material628_2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Model001_Material628_3} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Model001_Material628_4} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Model001_Material628_5} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Model001_Material628_6} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Model001_Material628_7} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Model001_Material628_8} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Model001_Material628_9} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Model001_Material628_10} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Model001_Material628_11} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Model001_Material628_12} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Model001_Material628_13} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Model001_Material628_14} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Model001_Material628_15} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Model001_Material628_16} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Model001_Material628_17} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Model001_Material628_18} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Model001_Material628_19} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Model001_Material628_20} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Model001_Material628_21} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Model001_Material628_22} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Model001_Material628_23} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Model001_Material628_24} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Model001_Material628_25} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Model001_Material628_26} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Model001_Material628_27} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Model001_Material628_28} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Model001_Material628_29} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Model001_Material628_30} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Model001_Material628_31} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Model001_Material628_32} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Model001_Material628_33} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Model001_Material628_34} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Model001_Material628_35} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Model001_Material628_36} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.Model001_Material628_37} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Model001_Material628_38} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Model001_Material628_39} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Model001_Material628_40} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Model001_Material628_41} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Model001_Material628_42} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Model001_Material628_43} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Model001_Material628_44} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Model001_Material628_45} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Model001_Material628_46} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.Model001_Material628_47} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.Model001_Material628_48} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.Model001_Material628_49} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Model001_Material628_50} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.Model001_Material628_51} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Model001_Material628_52} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.Model001_Material628_53} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Model001_Material628_54} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Model001_Material628_55} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.Model001_Material628_56} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.Model001_Material628_57} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Model001_Material628_58} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.Model001_Material628_59} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.Model001_Material628_60} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.Model001_Material628_61} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Model001_Material628_62} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.Model001_Material628_63} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Model001_Material628_64} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.Model001_Material628_65} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.Model001_Material628_66} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.Model001_Material628_67} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.Model001_Material628_68} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.Model001_Material628_69} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Model001_Material628_70} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.Model001_Material628_71} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.Model001_Material628_72} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.Model001_Material628_73} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.Model001_Material628_74} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.Model001_Material628_75} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.Model001_Material628_76} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.Model001_Material628_77} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.Model001_Material628_78} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.Model001_Material628_79} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.Model001_Material628_80} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.Model001_Material628_81} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.Model001_Material628_82} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Model001_Material628_83} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.Model001_Material628_84} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.Model001_Material628_85} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.Model001_Material628_86} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.Model001_Material628_87} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.Model001_Material628_88} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.Model001_Material628_89} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.Model001_Material628_90} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.Model001_Material628_91} />
        <mesh geometry={nodes.Object_102.geometry} material={materials.Model001_Material628_92} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.Model001_Material628_93} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.Model001_Material628_94} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.Model001_Material628_95} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.Model001_Material628_96} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.Model001_Material628_97} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
