/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: molignanoantonio12 (https://sketchfab.com/molignanoantonio12)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/airpods-max-92ccaa254d814e80965b76ed10f89553
Title: Airpods Max
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Airpods = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/airpods/scene.gltf')
  console.log(nodes);
  
  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={0.3}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.034, -46.818, -0.877]} rotation={[0, 0, 1.09]} scale={[-35.498, 31.413, 26.947]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.013']} />
          </group>
          <group position={[0.048, 37.753, -0.425]} rotation={[0, 0, 0.368]} scale={12.524}>
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_18.geometry} material={materials['Material.010']} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.012']} position={[0.795, -20.966, -0.556]} rotation={[-Math.PI, 0, 3.096]} scale={3.956} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.007']} position={[0.777, 24.91, -0.502]} rotation={[0, 0, 0.368]} scale={12.524} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.014']} position={[-12.865, -53.709, -0.069]} rotation={[Math.PI / 2, 0.503, -Math.PI / 2]} scale={46.543} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Material} position={[1.034, -46.818, -0.877]} rotation={[0, 0, 1.09]} scale={[-35.498, 31.413, 26.947]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material.009']} position={[1.302, -51.086, -0.747]} rotation={[Math.PI / 2, 0.503, -Math.PI / 2]} scale={46.543} />
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/airpods/scene.gltf')
