/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: King_45 (https://sketchfab.com/King_45)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wonder-women-multiversus-8005417022ca451f81354a9d7ccbc86a
Title: Wonder Women | MultiVersus
*/
'use client'
import React, {useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function SpartakWoman(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/spartak_woman/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions && animations.length > 0) {
      const actionName = animations[0].name // Берем первую анимацию
      actions[actionName]?.play() // Запускаем анимацию
    }
  }, [actions, animations])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="WW_BodySkelMesh_LOD0_Skeleton_425">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="WW_BodySkelMesh_LOD0_424" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['WonderWoman_Base_MIC.001']} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['WonderWoman_WeaponBase_MIC.001']} skeleton={nodes.Object_8.skeleton} />
                </group>
              </group>
              <group name="WW_Hair_SkelMesh_LOD0_Skeleton_851">
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="WW_Hair_SkelMesh_LOD0_850" />
                  <skinnedMesh name="Object_437" geometry={nodes.Object_437.geometry} material={materials['WonderWoman_Hair_MIC.001']} skeleton={nodes.Object_437.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spartak_woman/scene.gltf')
